/**
 * Generated by scripts/brand-mark.mjs. Do not edit by hand.
 *
 * The Vigil mark, as three frames of one 25 x 11 pixel grid. The
 * geometry, the invariants that keep a blink from moving the mark, and
 * the reasoning live in scripts/brand-mark.mjs.
 */

export const MARK_WIDTH = 25;
export const MARK_HEIGHT = 11;
export const MARK_VIEWBOX = "0 0 25 11";

export const MARK_FRAMES = {
  open: "M9 0h7v2h-7zM6 1h3v1h-3zM16 1h3v1h-3zM4 2h2v1h-2zM19 2h2v1h-2zM2 3h2v1h-2zM11 3h3v5h-3zM21 3h2v1h-2zM1 4h2v1h-2zM10 4h1v3h-1zM14 4h1v3h-1zM22 4h2v1h-2zM0 5h2v1h-2zM23 5h2v1h-2zM1 6h2v1h-2zM22 6h2v1h-2zM2 7h2v1h-2zM21 7h2v1h-2zM4 8h2v1h-2zM19 8h2v1h-2zM6 9h13v1h-13zM9 10h7v1h-7z",
  half: "M6 2h13v2h-13zM3 3h3v1h-3zM19 3h3v1h-3zM1 4h2v1h-2zM22 4h2v1h-2zM0 5h2v1h-2zM10 5h5v2h-5zM23 5h2v1h-2zM1 6h2v1h-2zM22 6h2v1h-2zM2 7h2v1h-2zM11 7h3v1h-3zM21 7h2v1h-2zM4 8h2v1h-2zM19 8h2v1h-2zM6 9h13v1h-13zM9 10h7v1h-7z",
  closed: "M4 4h17v3h-17zM0 5h4v1h-4zM21 5h4v1h-4z",
} as const;

export type MarkFrame = keyof typeof MARK_FRAMES;

/** Blink timing, in milliseconds. One blink is 180ms of frame swaps. */
export const BLINK = {
  minWait: 7000,
  maxWait: 15000,
  half: 60,
  closed: 70,
  reopen: 50,
  doubleChance: 0.25,
  doubleGap: 180,
} as const;
