/**
 * Generated by scripts/brand-mark.mjs. Do not edit by hand.
 *
 * The Vigil mark: two curved blades around a narrow waist, one path in a
 * 80 x 128 box. The geometry, its invariants and the reasoning live in
 * scripts/brand-mark.mjs. The mark is still; the pixel eye and its blink
 * retired together on 2026-08-17.
 *
 * MARK_PATH is the small optical cut: the application renders the mark at
 * chrome sizes, where the display cut's aperture would seal shut. The
 * display cut lives in docs/brand/ for anything set large.
 */

export const MARK_WIDTH = 80;
export const MARK_HEIGHT = 128;
export const MARK_VIEWBOX = "0 0 80 128";

export const MARK_PATH =
  "M8 4L30 14C37 46 37 82 30 114L8 124C17 82 17 46 8 4ZM72 4L50 14C43 46 43 82 50 114L72 124C63 82 63 46 72 4Z";
