import { randomUUID } from "node:crypto";

import { eq } from "drizzle-orm";
import { describe, expect, it } from "vitest";

import { monitors } from "@/db/schema";
import type { CreateMonitorInput } from "@/modules/monitors/schemas";
import {
  createMonitor,
  getMonitorDetail,
  updateMonitor,
} from "@/modules/monitors/service";
import { SECRET_MASK, redactConfig } from "@/modules/monitors/types/config";
import { CHECK_TYPE_SPECS, requireSpec } from "@/modules/monitors/types/specs";

import { createTestOrg, db } from "../helpers";

/**
 * A monitor's type-specific settings must survive an edit that does not
 * mention them.
 *
 * Before 1.13.0 they did not. `monitorColumnsFor` rebuilt the config
 * blob from the submission with `storedSchema.parse(input.config ?? {})`,
 * and the monitor form's `buildConfig()` returned `null` for twelve of
 * the fourteen types — so renaming a Redis monitor silently replaced its
 * config with all-defaults and dropped the password. The monitor then
 * failed authentication with nothing anywhere explaining why.
 *
 * Every type is covered, generated from the registry rather than listed
 * by hand, so a type added later cannot quietly skip this.
 */

/** A distinctive stored config per type — or null where a type has none. */
const CONFIGS: Record<string, Record<string, unknown> | null> = {
  http: null,
  tcp: null,
  ping: { packets: 4 },
  dns: { recordType: "MX", expectedValue: "mail.preserve.example" },
  "tls-expiry": { warnDays: 33 },
  "domain-expiry": { warnDays: 44 },
  postgres: null,
  mysql: null,
  mongodb: null,
  redis: { password: "sup3r-s3cret-redis" },
  docker: { containerName: "preserve-me", socketPath: "/var/run/docker.sock" },
  mqtt: { username: "preserve-user", password: "sup3r-s3cret-mqtt" },
  rabbitmq: { username: "preserve-user", password: "sup3r-s3cret-rabbit" },
  "kafka-producer": {
    topic: "preserve.orders",
    message: "vigil preserve check",
    username: "preserve-user",
    password: "sup3r-s3cret-kafka",
    tls: true,
  },
  smtp: null,
  // Both database types keep their credential in the connection string,
  // exactly as postgres does, so there is no config blob to lose.
  sqlserver: null,
  oracledb: null,
  ldap: {
    bindDn: "cn=vigil,ou=service,dc=preserve,dc=example",
    bindPassword: "sup3r-s3cret-ldap",
  },
  ssh: { expectedBanner: "OpenSSH_9" },
  imap: { requiredCapability: "STARTTLS" },
  ftp: { username: "preserve-user", password: "sup3r-s3cret-ftp" },
  "json-query": { jsonPath: "$.status.state", expectedValue: "ok" },
  globalping: {
    location: "Germany",
    probeLimit: 3,
    packets: 4,
    maxPacketLossPct: 20,
    apiToken: "globalping-secret-token",
  },
  "real-browser": {
    serviceUrl: "https://browserless.preserve.example",
    token: "browserless-secret-token",
    settleMs: 1_500,
  },
  sip: { transport: "tcp", requestUser: "vigil-probe" },
  snmp: {
    oid: "1.3.6.1.2.1.1.3.0",
    version: "2c",
    community: "preserve-community",
  },
  "system-service": null,
  "tailscale-ping": { packets: 4, requireDirect: true },
  websocket: {
    subprotocol: "graphql-ws",
    authorization: "sup3r-s3cret-websocket",
  },
  grpc: {
    service: "orders.v1.Orders",
    tls: true,
    authorization: "sup3r-s3cret-grpc",
  },
  // A push token is generated by the schema and never sent by the form,
  // so what has to survive an edit is the token nobody retyped — the
  // exact shape of the 1.13.0 bug, with an endpoint on the other end of
  // it that stops working the moment the value changes.
  push: { graceSeconds: 90 },
  group: null,
  manual: { status: "down", note: "vendor outage, ticket #4412" },
  memcached: {
    username: "preserve-user",
    password: "sup3r-s3cret-memcached",
    maxConnectionUsagePercent: 80,
  },
  elasticsearch: {
    username: "elastic",
    password: "sup3r-s3cret-elastic",
    minimumStatus: "yellow",
  },
  // A2S is unauthenticated and takes no settings, so this type keeps
  // everything it has in the flat columns — like smtp and tcp.
  steam: null,
  // The protocol is the only thing a game-server query needs, and the
  // monitor form has no section for it yet: `config: null` is exactly
  // what an edit sends today, which makes this type the current shape of
  // the 1.13.0 data-loss bug.
  gamedig: { protocol: "minecraft" },
  udp: {
    payload: "STATUS\n",
    payloadEncoding: "text",
    expectedResponse: "READY",
  },
  ntp: { maxOffsetMs: 250 },
  // Two credentials in one blob: the shared secret and a working login
  // on whatever the server authenticates against. Both are masked on
  // the way out, so both have to survive an edit that does not mention
  // them.
  radius: {
    secret: "sup3r-s3cret-radius",
    username: "preserve-user",
    password: "sup3r-s3cret-account",
    nasIdentifier: "preserve",
    expectAccept: true,
  },
};

/** A target each type's `targetSchema` accepts. */
const TARGETS: Record<string, string> = {
  http: "https://preserve.example.com/health",
  "json-query": "https://preserve.example.com/api",
  tcp: "db.preserve.example",
  ping: "host.preserve.example",
  dns: "preserve.example",
  "tls-expiry": "preserve.example",
  "domain-expiry": "preserve.example",
  postgres: "postgres://user:pw@db.preserve.example:5432/app",
  mysql: "mysql://user:pw@db.preserve.example:3306/app",
  mongodb: "mongodb://user:pw@db.preserve.example:27017/app",
  redis: "cache.preserve.example",
  docker: "docker.preserve.example",
  mqtt: "broker.preserve.example",
  rabbitmq: "https://rabbit.preserve.example:15672",
  "kafka-producer": "kafka.preserve.example",
  smtp: "mail.preserve.example",
  globalping: "globalping.preserve.example",
  "real-browser": "https://browser.preserve.example/app",
  sip: "sip.preserve.example",
  snmp: "switch.preserve.example",
  "system-service": "nginx.service",
  "tailscale-ping": "db-1",
  sqlserver: "sqlserver://user:pw@db.preserve.example:1433/app",
  // No credentials, on purpose: the Oracle check asks the listener about
  // a service and never signs in, so its schema refuses a password it
  // would only store.
  oracledb: "oracle://db.preserve.example:1521/ORCLPDB1",
  ldap: "ldap.preserve.example",
  ssh: "bastion.preserve.example",
  imap: "imap.preserve.example",
  ftp: "files.preserve.example",
  push: "nightly-backup",
  group: "EU region",
  manual: "Stripe payments",
  memcached: "cache.preserve.example",
  elasticsearch: "https://search.preserve.example:9200",
  steam: "cs.preserve.example",
  gamedig: "mc.preserve.example",
  udp: "collector.preserve.example",
  ntp: "time.preserve.example",
  radius: "radius.preserve.example",
  websocket: "wss://socket.preserve.example/live",
  grpc: "api.preserve.example",
};

const TYPE_IDS = Object.keys(CHECK_TYPE_SPECS);

function inputFor(checkType: string): CreateMonitorInput {
  const target = TARGETS[checkType];
  if (!target) throw new Error(`No test target for check type ${checkType}`);
  return {
    name: `preserve-${checkType}-${randomUUID().slice(0, 8)}`,
    url: target,
    method: "GET",
    intervalSeconds: 60,
    timeoutMs: 10_000,
    degradedThresholdMs: 3_000,
    expectedStatusCode: null,
    bodyKeyword: null,
    keywordAbsent: false,
    checkType,
    tlsCheck: false,
    tlsWarnDays: 14,
    failureWindowSeconds: 120,
    config: CONFIGS[checkType] ?? null,
  } as CreateMonitorInput;
}

async function storedConfig(monitorId: string): Promise<unknown> {
  const [row] = await db
    .select({ config: monitors.config })
    .from(monitors)
    .where(eq(monitors.id, monitorId));
  return row?.config ?? null;
}

describe("every check type keeps its config across an edit", () => {
  it("covers every type in the registry", () => {
    // The guard that makes the generated cases below meaningful: a new
    // type with no entry here fails immediately rather than being
    // silently skipped.
    expect(Object.keys(CONFIGS).sort()).toEqual([...TYPE_IDS].sort());
    expect(Object.keys(TARGETS).sort()).toEqual([...TYPE_IDS].sort());
  });

  it.each(TYPE_IDS)(
    "%s: an edit that says nothing about config leaves it alone",
    async (checkType) => {
      const actor = await createTestOrg();
      const monitor = await createMonitor(db, actor, inputFor(checkType));
      const afterCreate = await storedConfig(monitor.id);

      // Exactly what the monitor form sends for a type whose fields it
      // does not render: `config: null`. This was the data-loss path.
      await updateMonitor(db, actor, monitor.id, {
        name: `renamed-${randomUUID().slice(0, 8)}`,
        config: null,
      });

      expect(await storedConfig(monitor.id)).toEqual(afterCreate);
    },
  );

  it.each(TYPE_IDS)(
    "%s: an edit that omits config entirely leaves it alone",
    async (checkType) => {
      const actor = await createTestOrg();
      const monitor = await createMonitor(db, actor, inputFor(checkType));
      const afterCreate = await storedConfig(monitor.id);

      await updateMonitor(db, actor, monitor.id, {
        name: `renamed-${randomUUID().slice(0, 8)}`,
      });

      expect(await storedConfig(monitor.id)).toEqual(afterCreate);
    },
  );

  it.each(TYPE_IDS)(
    "%s: a create round-trips what was sent",
    async (checkType: string) => {
      const actor = await createTestOrg();
      const input = inputFor(checkType);
      const monitor = await createMonitor(db, actor, input);
      const stored = (await storedConfig(monitor.id)) as Record<
        string,
        unknown
      > | null;
      // `undefined` means this file has no entry for a registered type.
      // Thrown rather than skipped: a silently uncovered type is exactly
      // what the coverage assertion above exists to prevent.
      if (!(checkType in CONFIGS)) {
        throw new Error(`No expected config for check type ${checkType}`);
      }
      const expected = CONFIGS[checkType] ?? null;

      if (expected === null) {
        // The types that predate the blob store null, not `{}` — a second
        // place their settings could live is exactly what `flatColumnsOnly`
        // exists to prevent.
        expect(stored).toBeNull();
      } else {
        for (const [key, value] of Object.entries(expected)) {
          expect({ [key]: stored?.[key] }).toEqual({ [key]: value });
        }
      }
    },
  );
});

describe("partial config updates merge rather than replace", () => {
  it("changes one field and keeps the others", async () => {
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("mqtt"));

    await updateMonitor(db, actor, monitor.id, {
      config: { username: "renamed-user" },
    });

    const stored = (await storedConfig(monitor.id)) as Record<string, unknown>;
    expect(stored.username).toBe("renamed-user");
    expect(stored.password).toBe("sup3r-s3cret-mqtt");
  });

  it("drops the previous type's config when the type changes", async () => {
    // A config belongs to the type that wrote it. Merging a Redis blob
    // under the DNS schema would either fail validation or, where the
    // shapes overlap, carry a stale setting into a type that never asked
    // for it — and a later switch back would resurrect it.
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("redis"));

    await updateMonitor(db, actor, monitor.id, {
      checkType: "dns",
      url: "preserve.example",
      config: { recordType: "A", expectedValue: null },
    });

    const stored = (await storedConfig(monitor.id)) as Record<string, unknown>;
    expect(stored.password).toBeUndefined();
    expect(stored.recordType).toBe("A");
  });
});

describe("secret semantics are explicit", () => {
  it("keeps a secret when the client echoes the mask back", async () => {
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("redis"));

    await updateMonitor(db, actor, monitor.id, {
      config: { password: SECRET_MASK },
    });

    const stored = (await storedConfig(monitor.id)) as Record<string, unknown>;
    expect(stored.password).toBe("sup3r-s3cret-redis");
  });

  it("never writes the mask itself into the row", async () => {
    // If the sentinel ever reached storage the monitor would authenticate
    // with a literal placeholder, and the failure would look like a wrong
    // password rather than a bug.
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("mqtt"));
    await updateMonitor(db, actor, monitor.id, {
      config: { username: "u", password: SECRET_MASK },
    });
    const stored = JSON.stringify(await storedConfig(monitor.id));
    expect(stored).not.toContain(SECRET_MASK);
  });

  it("clears a secret when the client sends null", async () => {
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("redis"));

    await updateMonitor(db, actor, monitor.id, {
      config: { password: null },
    });

    const stored = (await storedConfig(monitor.id)) as Record<string, unknown>;
    expect(stored.password).toBeNull();
  });

  it("replaces a secret when the client sends a new value", async () => {
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("redis"));

    await updateMonitor(db, actor, monitor.id, {
      config: { password: "rotated-secret" },
    });

    const stored = (await storedConfig(monitor.id)) as Record<string, unknown>;
    expect(stored.password).toBe("rotated-secret");
  });

  it("masks stored secrets on the way out", async () => {
    const actor = await createTestOrg();
    const monitor = await createMonitor(db, actor, inputFor("redis"));
    const detail = await getMonitorDetail(db, actor.organizationId, monitor.id);

    const redacted = redactConfig(
      requireSpec("redis"),
      detail.monitor.config,
    ) as Record<string, unknown>;
    expect(redacted.password).toBe(SECRET_MASK);
    expect(JSON.stringify(redacted)).not.toContain("sup3r-s3cret-redis");
  });

  it("leaves an unset secret null rather than masking absence", async () => {
    // Masking a null would tell the operator a credential exists when
    // none does, and they would then be unable to clear a field that was
    // never set.
    const actor = await createTestOrg();
    const input = inputFor("redis");
    const monitor = await createMonitor(db, actor, {
      ...input,
      config: { password: null },
    });

    const redacted = redactConfig(
      requireSpec("redis"),
      await storedConfig(monitor.id),
    ) as Record<string, unknown>;
    expect(redacted.password).toBeNull();
  });

  it("declares a secret for every type whose stored schema holds one", () => {
    // A type that gains a credential field but forgets `secretFields`
    // would serialise it into a browser. This asserts the two stay in
    // step for the types that have one today.
    expect(requireSpec("redis").secretFields).toContain("password");
    expect(requireSpec("mqtt").secretFields).toContain("password");
    expect(requireSpec("ldap").secretFields).toContain("bindPassword");
  });
});
